class AppStrings {
  static const appName = 'InteriorDesign-link';
  static const helloWelcome = 'Hello, welcome back!';
  static const registerHere = 'Register Here!';
  static const loginToContinue = 'Login to continue';
  static const name = 'Full Name';
  static const email = 'Email';
  static const password = 'Password';
  static const dontHaveAccount = "Dont't have an account? ";
  static const alreadyhaveaccount = "Already have an account? ";
  static const login = 'Login';
  static const register = 'Register';
  static const signup = 'Sign up';
  static const signin = 'Sign in';
  static const submit = 'Submit';
  static const home = 'Home';
  static const favorites = 'Favorites';
  static const add = 'Add';
  static const messages = 'Messages';
  static const user = 'User';
  static const profile = 'Profile';
  static const edit = 'Edit';
  static const logout = 'Log out';
  static const editProfile = 'Edit Profile';
  static const phoneNumber = 'Phone number';
  static const location = 'Location';
  static const pdescription = 'Project Description';
  static const submitrequirement = 'Submit your requirements to designer';
}
